param([string]$EnvironmentFile = (Join-Path (Split-Path $PSScriptRoot -Parent) '.env.ebay.local'))

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path $PSScriptRoot -Parent
$date = '2026-09-14'
$packageRoot = Join-Path $projectRoot "작업중\패키지\$date"

function Read-EnvironmentFile([string]$Path) { $v=@{}; Get-Content -LiteralPath $Path | ForEach-Object { if($_ -match '^([^#=]+)=(.*)$'){$v[$matches[1].Trim()]=$matches[2].Trim().Trim('"')} }; $v }
function Write-JsonFile([string]$Path,$Value) { [IO.File]::WriteAllText($Path,($Value|ConvertTo-Json -Depth 80),[Text.UTF8Encoding]::new($false)) }
function Get-ItemSpecifics($Item,$Product) {
  $r=[ordered]@{}
  foreach($e in @($Item.ItemSpecifics.NameValueList)) { $n=[string]$e.Name; if($n -and $n -notmatch '(?i)California Prop'){$r[$n]=@($e.Value|ForEach-Object{[string]$_}|Where-Object{$_})} }
  $r['Brand']=@('Genuine Hyundai Mobis'); $r['Manufacturer Part Number']=@($Product.compactPart); $r['OE/OEM Part Number']=@($Product.compactPart); $r['Country of Origin']=@('Korea, Republic of'); $r
}
function Get-UsCompatibility($Item) { @($Item.ItemCompatibilityList.Compatibility | ForEach-Object { $o=[ordered]@{}; foreach($e in $_.NameValueList){$n=[string]$e.Name;$v=[string]$e.Value;if($n -and $v){$o[$n]=$v}}; if($o.Count){[pscustomobject]$o} }) }
function Invoke-AuJson([string]$Uri,[string]$Method,$Body=$null) { $h=@{Authorization="Bearer $script:auToken";'X-EBAY-C-MARKETPLACE-ID'='EBAY_AU';'Content-Language'='en-AU';Accept='application/json'}; $p=@{Uri=$Uri;Method=$Method;Headers=$h}; if($null-ne$Body){$p.ContentType='application/json';$p.Body=[Text.Encoding]::UTF8.GetBytes(($Body|ConvertTo-Json -Depth 30 -Compress))}; Invoke-RestMethod @p }
function Get-AuCatalogRows([string]$CategoryId,[string]$Make,[string]$Model) { $b=@{categoryId=$CategoryId;propertyFilters=@(@{propertyName='Make';propertyValue=$Make},@{propertyName='Model';propertyValue=$Model});propertyNames=@('Year','Make','Model','Submodel','Variant','Engine')}; $z=Invoke-AuJson 'https://api.ebay.com/sell/metadata/v1/compatibilities/get_multi_compatibility_property_values' 'POST' $b; @($z.compatibilities|ForEach-Object{$o=[ordered]@{};foreach($d in $_.compatibilityDetails){if($d.propertyValue){$o[[string]$d.propertyName]=[string]$d.propertyValue}};if($o.Count){[pscustomobject]$o}}) }
function Select-AuCompatibility($Product) { $all=@();$audit=@();foreach($t in $Product.auTargets){try{$rows=@(Get-AuCatalogRows $Product.categoryId $t.make $t.model)}catch{$audit+=[pscustomobject]@{make=$t.make;model=$t.model;catalog=0;selected=0;error=$_.Exception.Message};continue};$m=@($rows|Where-Object{$y=0;$ok=[int]::TryParse([string]$_.Year,[ref]$y)-and$y-ge$t.minYear-and$y-le$t.maxYear;$txt="$($_.Variant) $($_.Engine)";$ok-and([string]::IsNullOrWhiteSpace([string]$t.enginePattern)-or$txt-match$t.enginePattern)});$all+=$m;$audit+=[pscustomobject]@{make=$t.make;model=$t.model;catalog=$rows.Count;selected=$m.Count}};[pscustomobject]@{rows=@($all|Sort-Object Year,Make,Model,Submodel,Variant,Engine -Unique);audit=$audit} }
function New-Description([string]$Template,[string]$TemplateTitle,$Product) { $v=$Template.Replace($TemplateTitle,$Product.title);$rx=[regex]'⭐Genuine[^<]+';if(-not$rx.IsMatch($v)){throw"Description title missing: $($Product.part)"};$v=$rx.Replace($v,$Product.title,1);foreach($old in @('437112M1009P','43711-2M1009P','43711 2M1009P')){$v=$v.Replace($old,$Product.compactPart)};$v=$v.Replace('leather 6 speed MT gear shift knob lever',$Product.partWords).Replace('Leather 6 Speed MT Gear Shift Knob Lever',$Product.partWords).Replace('This part fits Hyundai Genesis Coupe 2009-2017.','This part fits the vehicles listed in the compatibility table.');if($v-match'(?i)43711[- ]?2M1009P|leather 6 speed|gear shift knob'){throw"Old template text remains: $($Product.part)"};$v }

$settings=Read-EnvironmentFile $EnvironmentFile; $script:auToken=$settings['EBAY_AU_USER_TOKEN'];$usToken=$settings['EBAY_US_ACCESS_TOKEN']
$usIdentity=Invoke-RestMethod 'https://apiz.ebay.com/commerce/identity/v1/user/' -Headers @{Authorization="Bearer $usToken"};$auIdentity=Invoke-RestMethod 'https://apiz.ebay.com/commerce/identity/v1/user/' -Headers @{Authorization="Bearer $script:auToken"}
if($usIdentity.username-ne'gandakorea'-or$usIdentity.registrationMarketplaceId-ne'EBAY_US'){throw'US identity mismatch'};if($auIdentity.username-ne'sihooshop'-or$auIdentity.registrationMarketplaceId-ne'EBAY_AU'){throw'AU identity mismatch'}

$petrol='(?i)(Petrol|Gas)'; $petrolHybrid='(?i)(Petrol|Gas|Hybrid|Electric|EV|Fuel Cell)'
$products=@(
 [pscustomobject]@{itemId='c7d789f4-3f79-49af-bb05-87cfa65ab412';reference='336419168441';part='54612-C1000';compactPart='54612C1000';categoryId='33590';usd='57.65';shipping='7day normal';title='⭐Genuine 54612C1000 Front Strut Bearing For Hyundai Kia 2015-2023';partWords='front strut bearing';usStores=@('45118245012','44760396012');auStores=@('/Hyundai/KONA','/Kia/NIRO');auTargets=@(
   @{make='Hyundai';model='Kona';minYear=2018;maxYear=2023;enginePattern=$petrolHybrid},@{make='Kia';model='Cerato';minYear=2019;maxYear=2023;enginePattern=$petrol},@{make='Kia';model='Niro';minYear=2017;maxYear=2023;enginePattern=$petrolHybrid},@{make='Kia';model='Seltos';minYear=2021;maxYear=2023;enginePattern=$petrol},@{make='Kia';model='Soul';minYear=2020;maxYear=2023;enginePattern=$petrol},@{make='Hyundai';model='IONIQ';minYear=2017;maxYear=2022;enginePattern=$petrolHybrid},@{make='Hyundai';model='Veloster';minYear=2019;maxYear=2022;enginePattern=$petrol},@{make='Kia';model='Sportage';minYear=2017;maxYear=2022;enginePattern=$petrol},@{make='Hyundai';model='Tucson';minYear=2016;maxYear=2021;enginePattern=$petrolHybrid},@{make='Hyundai';model='Elantra';minYear=2017;maxYear=2020;enginePattern=$petrol},@{make='Hyundai';model='i30';minYear=2018;maxYear=2020;enginePattern=$petrol},@{make='Kia';model='Optima';minYear=2016;maxYear=2020;enginePattern=$petrolHybrid},@{make='Hyundai';model='Sonata';minYear=2015;maxYear=2019;enginePattern=$petrolHybrid},@{make='Kia';model='Cadenza';minYear=2017;maxYear=2019;enginePattern=$petrol})},
 [pscustomobject]@{itemId='4fe9f411-09bc-443d-9c15-a1d266bcb825';reference='235089532797';part='55280-2T000';compactPart='552802T000';categoryId='262227';usd='151.76';shipping='7day fast';title='⭐Genuine 552802T000 Rear Trailing Arm RH For Kia Optima 2011-2016';partWords='rear trailing arm right';usStores=@('13146861012');auStores=@('/Kia/Optima');auTargets=@(@{make='Kia';model='Optima';minYear=2011;maxYear=2016;enginePattern=$petrolHybrid})},
 [pscustomobject]@{itemId='f57e6f80-b4f1-4af8-afe8-020cb98c379b';reference='156794019486';part='55270-2T000';compactPart='552702T000';categoryId='33580';usd='151.76';shipping='7day fast';title='⭐Genuine 552702T000 Rear Trailing Arm LH For Kia Optima 2011-2016';partWords='rear trailing arm left';usStores=@('13146861012');auStores=@('/Kia/Optima');auTargets=@(@{make='Kia';model='Optima';minYear=2011;maxYear=2016;enginePattern=$petrolHybrid})},
 [pscustomobject]@{itemId='0888ea6e-0522-4197-ad2b-3a205146d7c5';reference='156794012054';part='55270-2T000_55280-2T000';compactPart='552702T000 / 552802T000';categoryId='33580';usd='271.27';shipping='7day fast';title='⭐Genuine Rear Trailing Arm LH RH 2EA For Kia Optima 2011-2016';partWords='rear trailing arm left right set';usStores=@('13146861012');auStores=@('/Kia/Optima');auTargets=@(@{make='Kia';model='Optima';minYear=2011;maxYear=2016;enginePattern=$petrolHybrid})},
 [pscustomobject]@{itemId='954dd957-e171-4c3c-a928-4f72044d69d8';reference='257683988425';part='37460-2B006';compactPart='374602B006';categoryId='177698';usd='62.35';shipping='7day normal';title='⭐Genuine 374602B006 Alternator Bracket For Accent Veloster Forte Soul 1.6L';partWords='alternator bracket';usStores=@('13135350012','20622051012');auStores=@('/Hyundai/Accent','/Hyundai/Veloster');auTargets=@(@{make='Kia';model='Rio';minYear=2012;maxYear=2019;enginePattern='(?i)(1588cc|1591cc|1.6L).*Petrol'},@{make='Kia';model='Soul';minYear=2012;maxYear=2019;enginePattern='(?i)(1591cc|1.6L).*Petrol'},@{make='Kia';model='Cerato';minYear=2014;maxYear=2018;enginePattern='(?i)(1591cc|1.6L).*Petrol'},@{make='Hyundai';model='Accent';minYear=2012;maxYear=2017;enginePattern='(?i)(1591cc|1.6L).*Petrol'},@{make='Hyundai';model='Veloster';minYear=2012;maxYear=2017;enginePattern='(?i)(1591cc|1.6L).*Petrol'})},
 [pscustomobject]@{itemId='6093fb11-45f5-459f-8832-1b0b643bb5c5';reference='334813254928';part='87721-B8500GAL';compactPart='87721B8500GAL';categoryId='33654';usd='291.76';shipping='7day fast';title='⭐Genuine 87721B8500GAL Front Door Lower Molding LH For Santa Fe 2017-2018';partWords='front door lower molding left';usStores=@('45562724012','45455270012');auStores=@('/Hyundai/Santa Fe Sports','/Hyundai/Santa Fe XL');auTargets=@(@{make='Hyundai';model='Santa Fe';minYear=2017;maxYear=2018;enginePattern='(?i)(1998cc|2359cc|3342cc|2.0L|2.4L|3.3L).*Petrol'})}
)

[xml]$templateXml=Get-Content -Raw -LiteralPath (Join-Path $projectRoot '작업중\ebay-336779935333\item.xml');$template=$templateXml.GetItemResponse.Item
New-Item -ItemType Directory -Force -Path $packageRoot|Out-Null;$summary=@()
foreach($p in $products){
 [xml]$sx=Get-Content -Raw -LiteralPath (Join-Path $projectRoot "작업중\ebay-$($p.reference)\item.xml");$source=$sx.GetItemResponse.Item
 if(-not$p.title.StartsWith('⭐Genuine ')-or$p.title.Length-gt80){throw"Invalid title: $($p.title)"}
 $us=@(Get-UsCompatibility $source);if(-not$us.Count){throw"No US compatibility: $($p.part)"};$au=Select-AuCompatibility $p;if(-not$au.rows.Count){throw"No AU compatibility: $($p.part)"}
 $specifics=Get-ItemSpecifics $source $p;$desc=New-Description ([string]$template.Description) ([string]$template.Title) $p
 $m=[ordered]@{version=1;date=$date;itemId=$p.itemId;referenceItemNumber=$p.reference;partNumber=$p.part;usdPrice=$p.usd;shippingPolicy=$p.shipping;title=$p.title;descriptionHtml=$desc;type=$p.partWords;images=@();preparedAt=[DateTime]::UtcNow.ToString('o');us=[ordered]@{categoryId=$p.categoryId;storeCategoryIds=@($p.usStores);itemSpecifics=$specifics;compatibility=$us};au=[ordered]@{categoryId=$p.categoryId;storeCategoryNames=@($p.auStores);itemSpecifics=$specifics;compatibility=@($au.rows)}}
 Write-JsonFile (Join-Path $packageRoot "$($p.itemId).json") $m;Write-JsonFile (Join-Path $packageRoot "$($p.itemId)-au-audit.json") $au.audit
 $summary+=[pscustomobject]@{part=$p.part;titleLength=$p.title.Length;US=$us.Count;AU=@($au.rows).Count;images=@(Get-ChildItem -LiteralPath (Join-Path $projectRoot "완성본\$($p.part)") -Filter '*.png').Count;shipping=$p.shipping}
}
[pscustomobject]@{usIdentity=$usIdentity.username;auIdentity=$auIdentity.username;packages=$summary}|ConvertTo-Json -Depth 8
